USE [master]
GO

DBCC CHECKDB('batch') WITH NO_INFOMSGS,ALL_ERRORMSGS
GO

DBCC CHECKDB('import') WITH NO_INFOMSGS,ALL_ERRORMSGS
GO

DBCC CHECKDB('neptune') WITH NO_INFOMSGS,ALL_ERRORMSGS
GO

DBCC CHECKDB('stack') WITH NO_INFOMSGS,ALL_ERRORMSGS
GO

DBCC CHECKDB('student') WITH NO_INFOMSGS,ALL_ERRORMSGS
GO